version: "3.8"
services:
  ## alist-aria2
  ## docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 -e PUID=0 -e PGID=0 -e UMASK=022 --name="alist" xhofe/alist-aria2:latest
  alist:
    container_name: alist
    restart: always
    volumes:
        - /Users/I312313/Developer/docker/alist:/opt/alist/data
    ports:
        - 5244:5244
    environment:
        - PUID=0
        - PGID=0
        - UMASK=022
    image: xhofe/alist-aria2:latest
    networks:
      - local-dev
  ## Portainer
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9100:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/I312313/Developer/docker/portainer:/data
    networks:
      - local-dev
  ## Mysql
  mysql:
    container_name: mysql-dev
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: --lower_case_table_names=1
    networks:
      - local-dev
  ## PostgreSQL
  postgreSQL:
    container_name: postgreSQL-dev
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - /Users/I312313/Developer/docker/postgreSQL:/var/lib/postgresql/data
    networks:
      - local-dev
  ## Hana2
  hana2:
    container_name: hana2-dev
    image: docker.wdf.sap.corp:50000/bizx-database/hana2-rmda:trunk.weekly
    hostname: hana
    ports:
      - 30015:30015
    networks:
      - local-dev
  hanaIR:
    container_name: hanaIR-dev
    image: docker.wdf.sap.corp:50000/bizx-database/hana2-rmda:trunk.weekly
    hostname: hana
    ports:
      - 30115:30015
    volumes:
      - /Volumes/forhana:/data/instancerefresh
    networks:
      - local-dev
  ## Consul
  consul:
    container_name: consul-dev
    image: consul:latest
    ports:
      - 8500:8500/tcp
    command: "agent -server -ui -bootstrap-expect=1 -client=0.0.0.0"
    networks:
      - local-dev
  ## Redis
  redis:
    container_name: redis-dev
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - local-dev
volumes:
  data01:
    driver: local
  # data02:
  #   driver: local
networks:
  local-dev:
    driver: bridge